int32 cx # center x position of apriltag
int32 cy # center y position of apriltag
float32 tx # target x position for landing (old method that may be useful in alternative implementations)
float32 ty # target y position for landing (old method that may be useful in alternative implementations)
bool found # was an apriltag spotted
bool land # indicates whether ready to land when setting the next position (old method that may be useful in alternative implementations)