float32 dx # distance from front of depth camera to a detected apriltag
float32 dy # lateral distance to a detected apriltag, + values indicate apriltag is to the right of the camera
float32 yaw # relative heading of a detected apriltag to drone
float32 cx # x coordinate of detected apriltag center
float32 cy # y coordinate of detected apriltag center
bool spotted # true if an apriltag is detected